ASMPARAMS = --32
LDPARAMS = -melf_i386
GPPPARAMS = -m32 -fno-use-cxa-atexit -nostdlib -fno-builtin -fno-rtti -fno-exceptions -fno-leading-underscore

objects = kernel.o loader.o

%.o: %.cpp
    g++ $(GPPPARAMS) -o $@ -c $<

%.o: %.s
    as $(ASMPARAMS) -o $@ $<

mykernel.bin: linker.ld $(objects)
    ld $(LDPARAMS) -T $< -o $@ $(objects)

mykernel.ios: mykernel.bin
	mkdir iso
	mkdir iso/boot
	mkdir iso/boot/grub
	cp $< iso/boot
	echo 'set timeout = 5' >> iso/boot/grub.cfg
	echo 'set default = 0' >> iso/boot/grub.cfg
	echo '' >> iso/boot/grub.cfg
	echo 'menuentry "My Operating System ..." {' >> iso/boot/grub.cfg
	echo '  multinoot /boot/mykernel.bin' >> iso/boot/grub.cfg
	echo '  boot' >> iso/boot/grub.cfg
	echo '}' >> iso/boot/grub.cfg
	grub-mkrescue --output=$@ iso
	rm -f iso

.phony: clean
clean:
	rm -rf $(objects) mykernel.bin mykernel.iso